### ISSUE TITLE
ANSELD and ANSELF bits for p32mk1024gpd064

### ISSUE THREAD

**Issue by dr-begemot** [CyberCastle/PIC32-MCU-Compiler#3]
Why ANSELD and ANSELF bits not present for p32mk1024gpd064?
They was in microchip xc32 2.15, but disappeared with the release of 2.20, do you know why?
Thank!

**Comment by CyberCastle** [comment]
Hi

Sorry, I don't know why Microchip didn't include those definitions in the library.

Greetings
